In [1]:
import numpy as np


In [10]:
a = np.matrix([1,2])

In [15]:
a@a.T


matrix([[5]])

In [17]:
a*a.T

matrix([[5]])

In [18]:
np.multiply(a,a)

matrix([[1, 4]])

In [20]:
np.dot(a,a.T)

matrix([[5]])

In [22]:
a.dot(a.T)

matrix([[5]])

In [23]:
np.random.uniform(  size = 40)

array([0.21778501, 0.46770623, 0.1679473 , 0.25673874, 0.80290226,
       0.92041099, 0.20460979, 0.47254445, 0.67520106, 0.48276386,
       0.19896352, 0.63199347, 0.71484917, 0.24867531, 0.8477846 ,
       0.6944474 , 0.06663458, 0.47422116, 0.84822746, 0.95620122,
       0.54441604, 0.46474133, 0.93150439, 0.17219749, 0.35321949,
       0.44985008, 0.56879922, 0.97054145, 0.53190364, 0.28239525,
       0.37241984, 0.89010763, 0.42491289, 0.90344368, 0.08317923,
       0.94369239, 0.58242331, 0.01622506, 0.50614792, 0.99147974])